In [1]:
import numpy as np 

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 22 ms


In [5]:
%time for _ in range(10): my_list2 = my_list*2

Wall time: 222 ms


In [6]:
# The Numpy ndarray: A multidimensional Array Object

In [7]:
data = np.random.randn(2,3)

In [8]:
data

array([[ 1.48542788, -0.39782037, -0.43387587],
       [ 1.50132837,  0.61460125, -1.19347179]])

In [9]:
data * 10 

array([[ 14.85427876,  -3.9782037 ,  -4.33875866],
       [ 15.01328371,   6.14601253, -11.93471789]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
#Creating ndarrays

In [13]:
data1 = [6,7,5,8,0,1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6, 7, 5, 8, 0, 1])

In [16]:
data2 = [[2,3,4,5],[1,2,3,4] ]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[2, 3, 4, 5],
       [1, 2, 3, 4]])

In [19]:
arr2.ndim #ndim, how many arrays exist

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2,3,2))

array([[[9.97835521e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.23352354e+175]],

       [[1.34683541e+165, 2.85272591e-056],
        [9.41070759e-047, 1.73793518e-047],
        [2.57957888e-057, 8.07184539e+169]]])

In [25]:
#ndarray's astype method

In [26]:
arr = np.array([1,2,3,4,5])

In [27]:
arr.dtype

dtype('int32')

In [28]:
float_arr = arr.astype(np.float64)

In [29]:
float_arr.dtype

dtype('float64')

In [30]:
arr = np.array([3.7, 1.4, 5.6])

In [31]:
arr

array([3.7, 1.4, 5.6])

In [32]:
arr2 = arr.astype(np.int32)

In [33]:
arr

array([3.7, 1.4, 5.6])

In [34]:
arr2

array([3, 1, 5])

In [35]:
#Arithmetic with Numpy arrays

In [36]:
arr = np.array([1.4, 1., 2., 8.])

In [37]:
arr

array([1.4, 1. , 2. , 8. ])

In [38]:
arr*arr

array([ 1.96,  1.  ,  4.  , 64.  ])

In [39]:
arr - arr

array([0., 0., 0., 0.])

In [40]:
arr ** 5

array([5.37824e+00, 1.00000e+00, 3.20000e+01, 3.27680e+04])

In [41]:
arr2 = np.array([[0.4, 3.], [ 7.1,8.4, 1.3]])

In [42]:
arr2

array([list([0.4, 3.0]), list([7.1, 8.4, 1.3])], dtype=object)

In [43]:
arr1

array([6, 7, 5, 8, 0, 1])

In [44]:
arr2 - arr1

ValueError: operands could not be broadcast together with shapes (2,) (6,) 

In [45]:
arr1 = np.array([1,2,7])

In [46]:
arr2 = np.array([[2,3,4],[5,6,7]])

In [47]:
arr2 - arr1

array([[ 1,  1, -3],
       [ 4,  4,  0]])

In [48]:
arr2 <= arr1

array([[False, False,  True],
       [False, False,  True]])

In [49]:
#Basic Indexing and Slicing

In [50]:
arr = np.arange(10)

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[5]

5

In [53]:
arr[5:8]

array([5, 6, 7])

In [54]:
arr[5:8] = 12

In [55]:
arr_slice = arr[5:8]

In [56]:
arr_slice

array([12, 12, 12])

In [57]:
arr_slice[1] = 12345

In [58]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [59]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[0][2]

3

In [62]:
arr2d[2][1]

8

In [63]:
#Indexing elements in a Numpy array

In [64]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [65]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr3d[0][1][2]

6

In [68]:
old_values = arr3d[0].copy()

In [69]:
arr3d[0] = 42

In [70]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0] = old_values

In [73]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr3d.shape

(2, 2, 3)

In [75]:
arr3d[1,0]

array([7, 8, 9])

In [76]:
x = arr3d[1]

In [77]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [78]:
x[0]

array([7, 8, 9])

In [79]:
#Indexing with Slices

In [80]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [81]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [82]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [85]:
arr2d[1, :2]

array([4, 5])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[:2, 2]

array([3, 6])

In [89]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [91]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [92]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [93]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [95]:
arr2d[2,:]

array([7, 8, 9])

In [96]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [97]:
arr2d[1,:2]

array([4, 5])

In [98]:
#Boolean Indexing

In [99]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [100]:
data = np.random.randn(7,4)

In [101]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [102]:
data

array([[ 1.36337998,  1.13220799, -0.96145694, -1.33566457],
       [-0.2929329 , -0.79485616,  0.29818666, -0.69909837],
       [ 0.15494236,  0.05026144, -0.02180801, -1.00095523],
       [-1.02106009,  0.15719584, -0.08657167,  0.59857097],
       [ 0.66468518,  1.8824965 ,  0.12699344, -0.14935036],
       [ 0.50862003,  0.75259951,  0.1025918 , -1.07630203],
       [ 1.10725031, -0.49315461,  0.03439816, -1.35098978]])

In [103]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [104]:
data[names == 'Bob']

array([[ 1.36337998,  1.13220799, -0.96145694, -1.33566457],
       [-1.02106009,  0.15719584, -0.08657167,  0.59857097]])

In [105]:
data[names == 'Bob',:2]

array([[ 1.36337998,  1.13220799],
       [-1.02106009,  0.15719584]])

In [106]:
data[names == 'Bob',3]

array([-1.33566457,  0.59857097])

In [107]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [108]:
data[(names != 'Bob')]

array([[-0.2929329 , -0.79485616,  0.29818666, -0.69909837],
       [ 0.15494236,  0.05026144, -0.02180801, -1.00095523],
       [ 0.66468518,  1.8824965 ,  0.12699344, -0.14935036],
       [ 0.50862003,  0.75259951,  0.1025918 , -1.07630203],
       [ 1.10725031, -0.49315461,  0.03439816, -1.35098978]])

In [109]:
mask = (names == 'Bob') | (names == 'Will')

In [110]:
data[mask]

array([[ 1.36337998,  1.13220799, -0.96145694, -1.33566457],
       [ 0.15494236,  0.05026144, -0.02180801, -1.00095523],
       [-1.02106009,  0.15719584, -0.08657167,  0.59857097],
       [ 0.66468518,  1.8824965 ,  0.12699344, -0.14935036]])

In [111]:
data[data < 0] = 0 

In [112]:
data

array([[1.36337998, 1.13220799, 0.        , 0.        ],
       [0.        , 0.        , 0.29818666, 0.        ],
       [0.15494236, 0.05026144, 0.        , 0.        ],
       [0.        , 0.15719584, 0.        , 0.59857097],
       [0.66468518, 1.8824965 , 0.12699344, 0.        ],
       [0.50862003, 0.75259951, 0.1025918 , 0.        ],
       [1.10725031, 0.        , 0.03439816, 0.        ]])

In [113]:
data[names != 'Joe'] = 7 

In [114]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.29818666, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.50862003, 0.75259951, 0.1025918 , 0.        ],
       [1.10725031, 0.        , 0.03439816, 0.        ]])

In [115]:
#Fancy Indexing

In [116]:
arr = np.empty((8,4))

In [117]:
arr

array([[1.33511290e-306, 5.00690425e-308, 1.95819673e-306,
        7.56598449e-307],
       [3.11527486e-307, 1.86920193e-306, 1.69119330e-306,
        2.58125272e-306],
       [1.24610587e-306, 1.86920193e-306, 3.56046109e-307,
        4.22800362e-307],
       [1.37962185e-306, 1.44632687e-307, 9.34610469e-307,
        4.22793232e-307],
       [2.33644299e-307, 2.22520797e-307, 1.89142652e-307,
        2.22519099e-307],
       [4.45036841e-307, 2.78145776e-307, 1.44635488e-307,
        9.34609111e-307],
       [2.11397635e-307, 1.78021527e-306, 2.11398484e-307,
        1.37962185e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37960147e-306,
        1.33511562e-306]])

In [118]:
for i in range(8):
    arr[i] = i

In [119]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [120]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [121]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [122]:
arr = np.arange(32).reshape((8,4))

In [123]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [124]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [125]:
arr[[4,6,1],[1,2,0]]

array([17, 26,  4])

In [126]:
arr[[3,5,7],[2,3,1]]

array([14, 23, 29])

In [132]:
arr[[1,5,7,2]],[[0,3,1,2]]

(array([[ 4,  5,  6,  7],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [ 8,  9, 10, 11]]),
 [[0, 3, 1, 2]])

In [134]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [129]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [130]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
#Transposing Arrays and Swapping Axes

In [137]:
arr = np.arange(15).reshape((3,5))

In [138]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [140]:
arr = np.random.randn(6,3)

In [141]:
arr

array([[ 1.22234995, -0.85117886,  1.14991877],
       [ 0.5269823 , -0.13263936, -0.23667815],
       [ 0.50035066,  0.50761513, -0.30330318],
       [-0.57326367,  1.58718846, -0.58517808],
       [-0.13191305, -0.70243252, -0.26829565],
       [ 0.05781966,  0.75990109, -0.03767765]])

In [146]:
np.dot(arr.T, arr)

array([[ 2.37157593, -1.62963172,  1.49779453],
       [-1.62963172,  4.58980008, -1.87031459],
       [ 1.49779453, -1.87031459,  1.88615809]])

In [147]:
arr= np.arange(16).reshape((2,2,4))

In [148]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [156]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [157]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [160]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [161]:
#Universal Functions: Fast Element-Wise Array Function

In [162]:
arr = np.arange(10)

In [163]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [165]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [166]:
x = np.random.randn(8)

In [167]:
y = np.random.randn(8)

In [168]:
x

array([-0.99974668, -0.2796039 ,  1.63816872,  0.82897498,  1.89101088,
        0.95819689,  0.69840239,  0.70831572])

In [169]:
y

array([ 1.12919913, -1.20294686,  0.42257027, -0.09835832, -0.39258369,
       -0.11152414,  0.58728162, -2.07251502])

In [171]:
np.maximum(x,y)

array([ 1.12919913, -0.2796039 ,  1.63816872,  0.82897498,  1.89101088,
        0.95819689,  0.69840239,  0.70831572])

In [172]:
arr = np.random.randn(7)*5

In [173]:
arr

array([ 5.68540929,  3.16808118,  6.60667985,  1.61993862,  5.32429319,
       -8.49978734, -0.70040388])

In [174]:
remainder,whole_part = np.modf(arr)

In [175]:
remainder

array([ 0.68540929,  0.16808118,  0.60667985,  0.61993862,  0.32429319,
       -0.49978734, -0.70040388])

In [176]:
whole_part

array([ 5.,  3.,  6.,  1.,  5., -8., -0.])

In [177]:
arr

array([ 5.68540929,  3.16808118,  6.60667985,  1.61993862,  5.32429319,
       -8.49978734, -0.70040388])

In [179]:
np.sqrt(arr)

array([2.38440963, 1.77991044, 2.57034625, 1.27276809, 2.307443  ,
              nan,        nan])

In [180]:
np.sqrt(arr,arr)

array([2.38440963, 1.77991044, 2.57034625, 1.27276809, 2.307443  ,
              nan,        nan])

In [181]:
arr

array([2.38440963, 1.77991044, 2.57034625, 1.27276809, 2.307443  ,
              nan,        nan])

In [182]:
#Array Oriented Programming with Arrays

In [183]:
points = np.arange(-5,5,0.01) #Equally spaced points

In [185]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [186]:
xs,ys = np.meshgrid(points, points)

In [187]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [188]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [189]:
z = np.sqrt(xs**2 + ys**2)

In [190]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [198]:
import matplotlib.pyplot as plt

In [201]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5, 1.0, 'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [202]:
#Expressing COnditional Logic as Array Operations

In [203]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

In [205]:
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [206]:
cond = np.array([True,False,True,True,False])

In [207]:
result = [(x if c else y)
    for x,y,c in zip(xarr,yarr, cond)]

In [208]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [211]:
result = np.where(cond,yarr,xarr)

In [212]:
result

array([2.1, 1.2, 2.3, 2.4, 1.5])

In [213]:
arr = np.random.randn(4,4)

In [214]:
arr

array([[ 0.73844585, -0.12613923, -1.3469479 ,  0.49665966],
       [ 0.97892599, -0.13734008, -0.21825231,  1.15444841],
       [-0.37354688, -1.32524054, -1.31297367, -0.27925021],
       [-0.57259093,  1.11936183,  0.46238601,  0.63855439]])

In [215]:
arr > 0 

array([[ True, False, False,  True],
       [ True, False, False,  True],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [216]:
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [-2, -2, -2, -2],
       [-2,  2,  2,  2]])

In [218]:
np.where(arr > 0,2,'x')

array([['2', 'x', 'x', '2'],
       ['2', 'x', 'x', '2'],
       ['x', 'x', 'x', 'x'],
       ['x', '2', '2', '2']], dtype='<U11')

In [219]:
arr

array([[ 0.73844585, -0.12613923, -1.3469479 ,  0.49665966],
       [ 0.97892599, -0.13734008, -0.21825231,  1.15444841],
       [-0.37354688, -1.32524054, -1.31297367, -0.27925021],
       [-0.57259093,  1.11936183,  0.46238601,  0.63855439]])

In [220]:
# Mathemical and Stadistical Methods (reductions)

In [3]:
import numpy as np

In [4]:
arr = np.random.randn(5,4)

In [5]:
arr

array([[ 0.36024894, -0.56627484, -0.54629282,  0.68975977],
       [ 0.33220573, -0.45336284,  1.12575761, -2.40882793],
       [-1.61922082,  1.02256973, -0.38507179, -1.81848729],
       [-0.29459553, -1.25972457, -0.52786865,  1.01678564],
       [-1.46841923,  0.28990138, -0.14055595,  0.08457116]])

In [6]:
arr.mean()

-0.32834511563864577

In [7]:
np.mean(arr)

-0.32834511563864577

In [8]:
arr.sum()

-6.566902312772916

In [9]:
arr.mean(axis=1)

array([-0.01563974, -0.35105686, -0.70005254, -0.26635078, -0.30862566])

In [10]:
arr.sum(axis = 0 )

array([-2.68978091, -0.96689115, -0.47403161, -2.43619865])

In [11]:
arr.mean(1)

array([-0.01563974, -0.35105686, -0.70005254, -0.26635078, -0.30862566])

In [12]:
arr = np.array([0,1,2,3,4,5,6,7])

In [13]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [19]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [21]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [22]:
#Method and Boolean Arrays

In [23]:
arr = np.random.randn(100)

In [25]:
(arr > 0).sum() #number of positive values 

51

In [26]:
bools = np.array([False, False, True, False])

In [27]:
bools.any()

True

In [28]:
bools.all()

False

In [29]:
#Sorting

In [30]:
arr = np.random.randn(6)

In [31]:
arr

array([ 1.48305705, -0.35050562, -0.1345571 ,  0.73703782,  0.21467955,
        1.96716529])

In [32]:
arr.sort()

In [35]:
arr

array([-0.35050562, -0.1345571 ,  0.21467955,  0.73703782,  1.48305705,
        1.96716529])

In [36]:
arr = np.random.randn(5,3)

In [37]:
arr

array([[ 0.29004156, -1.67120498,  0.40720382],
       [-1.8248891 ,  0.09233473,  0.42051528],
       [ 0.59830645,  0.0162104 ,  0.49537747],
       [-0.10102192, -0.43407023,  1.01040908],
       [ 0.18350015,  0.20109607, -0.68289771]])

In [38]:
arr.sort(1)

In [39]:
arr

array([[-1.67120498,  0.29004156,  0.40720382],
       [-1.8248891 ,  0.09233473,  0.42051528],
       [ 0.0162104 ,  0.49537747,  0.59830645],
       [-0.43407023, -0.10102192,  1.01040908],
       [-0.68289771,  0.18350015,  0.20109607]])

In [41]:
large_arr = np.random.randn(1000)

In [42]:
large_arr

array([-2.70441158e-01,  8.19805514e-01,  1.87540066e+00,  6.97156688e-01,
       -7.66447612e-02,  6.40883633e-01, -6.06698605e-01, -4.28112543e-01,
       -1.54267454e+00,  7.32005731e-01, -1.71942252e+00,  5.83296110e-01,
        4.50411788e-01, -7.56119614e-01, -5.22742757e-01,  1.81267617e+00,
       -1.87609178e+00,  6.25792194e-01,  2.21835507e-02, -1.05719806e+00,
       -5.05767209e-01, -1.90094173e+00, -2.35008214e+00,  3.34950075e-01,
       -9.27790844e-01, -6.22371324e-01, -5.93291851e-01, -2.35326504e-01,
        1.17149041e+00, -1.63764447e+00, -1.13812485e+00,  6.45247382e-02,
        5.58841445e-01,  1.94176884e-01, -1.55894318e+00,  3.52095226e-01,
       -3.31252543e-01,  1.77923778e+00, -9.26425169e-01, -8.41303253e-03,
        4.60722103e-01, -6.08603377e-01,  4.13034790e-01, -1.20162406e+00,
       -2.07272863e+00, -3.25737280e-01,  1.10444658e+00, -8.83239520e-01,
        5.47625263e-01, -1.98932231e+00, -4.89843359e-01, -5.13456854e-01,
       -2.21814027e+00,  

In [43]:
large_arr.sort()

In [45]:
large_arr[int(0.05*len(large_arr))]# 5% quantile

-1.6417517829285706

In [46]:
# Unique and Ohter Set Logic

In [47]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [48]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [49]:
ints = np.array([3,3,3,2,2,1,1,4,4])

In [50]:
np.unique(ints)

array([1, 2, 3, 4])

In [52]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [53]:
values = np.array([6,0,0,3,2,5,6])

In [54]:
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [55]:
#File Imput and Output with Arrays

In [56]:
arr = np.arange(10)

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.save('some_array', arr)

In [68]:
np.load('array_archive.npz')

In [70]:
np.load('array_archive.npz')

In [71]:
np.savez('array_archive.npz', a=arr, b=arr)

In [72]:
arch = np.load('array_archive.npz')

In [73]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
#Lineal Algebra

In [76]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])

In [77]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [78]:
y = np.array([[6.,23.],[-1,7],[8,9]])

In [79]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [80]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [81]:
a = 2 + 3j

In [82]:
b = 4 + 5j

In [83]:
np.dot(a,b)

(-7+22j)

In [84]:
arr1 = [1,2]
arr2 = [6,5]

In [85]:
np.dot(arr1,arr2)

16

In [86]:
from numpy.linalg import inv, qr

In [87]:
X = np.random.randn(5,5)

In [88]:
mat = X.T.dot(X)

In [89]:
inv(mat)

array([[ 0.21091941,  0.24076099, -0.12693995,  0.18251335, -0.15811643],
       [ 0.24076099,  0.59774891, -0.08356024,  0.32339079, -0.36518106],
       [-0.12693995, -0.08356024,  0.56167986, -0.15950168,  0.13823267],
       [ 0.18251335,  0.32339079, -0.15950168,  0.60820317, -0.40087413],
       [-0.15811643, -0.36518106,  0.13823267, -0.40087413,  0.53413354]])

In [90]:
q,r = qr(mat)

In [91]:
r

array([[-1.15897653e+01,  5.37453679e+00, -2.14284753e+00,
         1.71038598e+00,  2.23204856e+00],
       [ 0.00000000e+00, -3.24598273e+00,  2.80329511e-01,
        -5.57287900e-03, -3.21049613e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.96109102e+00,
        -7.63183494e-01,  6.92728844e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -3.96781397e+00, -3.98990476e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.26646725e+00]])

In [92]:
#Pseaudorandom Number Generator

In [94]:
samples = np.random.normal(size=(4,4))

In [95]:
samples

array([[ 0.80733632,  0.6441919 ,  1.35176137,  0.64024824],
       [-1.11674742,  0.8092325 ,  0.92644149,  0.15375982],
       [-1.46859404,  0.66216135,  0.51811688,  0.74974383],
       [ 0.67996472,  0.29708192, -2.00479724, -0.716426  ]])

In [97]:
from random import normalvariate

In [98]:
N = 1000000

In [99]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

722 ms ± 9.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [101]:
%timeit np.random.normal(size=N)

22.2 ms ± 198 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [102]:
#Example: Random Walks

In [115]:
import matplotlib.pyplot as plt 
import numpy as np 

In [119]:
import random
position = 0 
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
      
    position += step
    walk.append(position)

In [121]:
plt.plot(walk[:100])

In [123]:
## Coin Flips at once

In [124]:
nsteps = 1000

In [125]:
draws = np.random.randint(0,2,nsteps)

In [126]:
draws

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [127]:
steps = np.where(draws > 0, 1, -1)

In [128]:
walk = steps.cumsum()

In [129]:
steps

array([-1, -1,  1, -1, -1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1, -1, -1,
        1,  1, -1,  1, -1, -1, -1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,
       -1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1,
        1,  1,  1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,
       -1, -1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1,
        1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1,
       -1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1,  1, -1,
       -1,  1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1, -1,
       -1, -1,  1, -1,  1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1,
       -1, -1, -1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1, -1,  1,
        1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,  1,  1,  1, -1, -1,
       -1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  1,
       -1, -1, -1, -1, -1

In [131]:
walk

array([ -1,  -2,  -1,  -2,  -3,  -2,  -3,  -4,  -3,  -4,  -3,  -4,  -5,
        -6,  -5,  -6,  -7,  -6,  -5,  -6,  -5,  -6,  -7,  -8,  -9,  -8,
        -9,  -8,  -9,  -8,  -7,  -6,  -7,  -8,  -9, -10,  -9, -10, -11,
       -12, -13, -14, -15, -14, -15, -16, -17, -18, -17, -18, -17, -16,
       -15, -14, -15, -16, -17, -16, -17, -16, -17, -16, -17, -16, -15,
       -14, -15, -14, -15, -16, -15, -16, -15, -16, -17, -18, -17, -16,
       -15, -14, -13, -14, -13, -14, -13, -12, -11, -10, -11, -10,  -9,
       -10, -11, -12, -13, -14, -15, -14, -13, -12, -13, -14, -13, -12,
       -13, -14, -15, -14, -13, -14, -13, -14, -15, -16, -15, -16, -17,
       -16, -17, -18, -17, -16, -17, -18, -17, -18, -17, -18, -17, -16,
       -15, -16, -17, -16, -15, -16, -17, -16, -17, -16, -17, -18, -17,
       -18, -17, -16, -15, -14, -15, -16, -15, -16, -17, -18, -19, -18,
       -19, -18, -17, -18, -17, -18, -19, -18, -19, -18, -19, -20, -19,
       -20, -21, -22, -23, -24, -23, -22, -23, -24, -23, -22, -2

In [132]:
walk.min()

-43

In [133]:
walk.max()

22

In [136]:
(np.abs(walk) >=10).argmax()

35

In [137]:
#Simulating Many Random Walks at Once

In [138]:
nwalks = 5000

In [139]:
nsteps = 1000

In [153]:
draws = np.random.randint(0,2,size=(nwalks,nsteps)) # 0 or 1

In [157]:
steps = np.where(draws > 0,1,-1)

In [158]:
walks = steps.cumsum(1)

In [159]:
walks

array([[  1,   0,  -1, ..., -16, -15, -16],
       [ -1,  -2,  -3, ...,  22,  21,  20],
       [  1,   0,  -1, ...,  38,  37,  38],
       ...,
       [  1,   2,   1, ..., -14, -13, -12],
       [ -1,   0,  -1, ...,   4,   3,   2],
       [  1,   0,   1, ...,  10,  11,  12]], dtype=int32)

In [160]:
walks.max()

120

In [161]:
walks.min()

-132

In [162]:
hits30 = (np.abs(walks) >=30).any(1)

In [163]:
hits30

array([False,  True,  True, ...,  True, False,  True])

In [164]:
hits30.sum()

3461

In [165]:
crossing_Times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [166]:
crossing_Times

array([789, 809, 677, ..., 761, 761, 233], dtype=int64)

In [168]:
crossing_Times.mean()

509.32591736492344